

export const imagesDBList = [
    '1.6q2.png',
    '8.1-q2-p-1.png',
    '8.1-q2-p-2.png',
    '8.1-q2-p-3.png',
    '8.1-q2-p-5.png',
    'activity1.jpg',
    'antilog1.jpg',
    'antilog2.jpg',
    'antilog3.jpg',
    'antilog4.jpg',
    'atom.png',
    'average speed.png',
    'baloons.png',
    'banners.png',
    'black_board.jpg',
    'board_classroom.jpg',
    'car showing speed (1).png',
    'car showing speed.png',
    'carbon-atom.png',
    'drops.png',
    'ex4.1-q2_matrix_multiplication.png',
    'female_teacher.jpg',
    'helium-atom.png',
    'hydrongen-atom.png',
    'logtable1.jpg',
    'logtable2.jpg',
    'logtable3.jpg',
    'logtable4.jpg',
    'mad_scientist.jpg',
    'moving car with arrows.jpg',
    'multiplication_step-0.png',
    'multiplication_step-01.png',
    'multiplication_step-02.png',
    'multiplication_step-03.png',
    'multiplication_step-04.png',
    'oxygen-atom.png',
    'pattern_waves.png',
    'people.png',
    'solarsystem.jpg',
    'taleem_classroom.jpg',
    'teacher_facing_board.jpg',
    'teen_boy.jpg',
    'test.png',
    'text2-4-8-6.png',
    'theorem10.1.1.png',
    'theorem10.1.2.png',
    'wood.jpg'
  ];